ci script update

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -1,7 +1,14 @@
-name: .NET
-defaults:
-  run:
-    shell: pwsh
+name: CI
+
+permissions:
+  pages:
+    write
+  contents:
+    write
+  pull-requests:
+    write
+  id-token:
+    write
 
 on:
   push:
@@ -18,29 +25,37 @@ on:
       - synchronize
   
   workflow_dispatch:
-    
     inputs:
-      
+      versionPrefix:
+        type: string
+        description: Prefix (e.g 1.1.1)
+        default: ""
+
       versionSuffix:
-        required: false
-        description: "Version suffix for nupkg"
-      
-      publishRelease:
-        required: true
+        type: string
+        description: Suffix (e.g alpha.1)
+        default: ""
+
+      publish:
         type: boolean
-        description: "Nuget release?"
+        description: run dotnet publish?
+        default: true
+
+      removePrereleases:
+        type: boolean
+        description: nuget unlist preleases?
         default: false
-      
+
       configuration:
-        required: false
+        description: build configuration
         default: Release
         type: choice
         options:
           - Debug
           - Release
-      
+
       verbosity:
-        required: false
+        description: build log verbosity
         default: minimal
         type: choice
         options:
@@ -51,105 +66,109 @@ on:
           - diagnostic
 
 jobs:
-  environment:
+
+  parameters:
     runs-on: ubuntu-latest
-    
-    concurrency:
-      group: ci-${{ github.ref }}
-      cancel-in-progress: false
     
     outputs:
-      versionSuffix: ${{ steps.defaults.outputs.versionSuffix }}
-      verbosity: ${{ steps.defaults.outputs.verbosity }}
-      configuration: ${{ steps.defaults.outputs.configuration }}
-      publishRelease: ${{ steps.defaults.outputs.publishRelease }}
+      versionSuffix: ${{ steps.parameters.outputs.versionSuffix }}
+      versionPrefix: ${{ steps.parameters.outputs.versionPrefix }}
+      configuration: ${{ steps.parameters.outputs.configuration }}
+      verbosity: ${{ steps.parameters.outputs.verbosity }}
+      publish: ${{ steps.parameters.outputs.publish }}
+      package: ${{ steps.parameters.outputs.package }}
+      publishSymbols: ${{ steps.parameters.outputs.publishSymbols }}
+      removePrereleases: ${{ steps.parameters.outputs.removePrereleases }}
+      runTests: ${{ steps.parameters.outputs.runTests }}
+      runCoverage: ${{ steps.parameters.outputs.runCoverage }}
 
     steps:
 
-      - name: Git Information
-        shell: bash
-        run: |
-          echo "head: $GITHUB_HEAD_REF"
-          echo "base: $GITHUB_BASE_REF"
-          echo "base: $GITHUB_REF"
-
-      - name: declare default values
-        id: defaults
-        shell: pwsh
-        run: |
-          $suffixMap = @{
-              "push"="alpha.${{github.run_number}}"; 
-              "pull_request"="beta.${{github.run_number}}"; 
-              "workflow_dispatch"="${{github.event.inputs.versionSuffix}}"
-          };
-          $suffix = $($suffixMap['${{github.event_name}}'])
-          if( $suffixMap['workflow_dispatch'] -ne '' -and '${{github.event_name}}' -eq 'workflow_dispatch'){
-              $suffix = $($suffix.TrimEnd('.') + ".")
-              $suffix = "$($suffix)${{github.run_number}}"
-          }  
-          
-          #   key name                workflow value                                  fallback value
-          $values = @(
-              @("versionSuffix",      "$suffix",                                      "$suffix"),
-              @("configuration",      "${{github.event.inputs.configuration}}",       "Release"),
-              @("verbosity",          "${{github.event.inputs.verbosity}}",           "minimal"),
-              @("publishRelease",     "${{github.event.inputs.publishRelease}}",      "true")
-          );
-
-          $manual = $('${{github.event_name}}' -eq 'workflow_dispatch')
-          foreach($pair in $values){
-              $value = $pair[2]
-              if($manual -eq $true){
-                  $value = $pair[1]
-              }
-
-              Write-Host "Setting parameter $($pair[0]) => $value"
-              echo "$($pair[0])=$value" >> $env:GITHUB_OUTPUT
-          }   
-  
-  build:
-    if: true
-    runs-on: ubuntu-latest
-    needs: environment
-
-    steps:
-      - name: Dump environment outputs
-        if: false
-        shell: bash
-        run: |
-          echo "${{ toJson( needs.environment.outputs) }}" > env_outputs.json
-          echo "${{ toJson( github) }}" > env_outputs.json
-        
-      - name: Display environment outputs
-        if: false
-        shell: bash
-        run: cat env_outputs.json
-        
-      - name: stop
-        if: false
-        run: exit 1
-      
-      - uses: actions/checkout@v4.1.7
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v4.0.1
-        with:
-          dotnet-version: 6.0.x
-
-      - name: Restore dependencies
-        run: dotnet restore src/All.sln
-      - name: Build
-        run: dotnet build src/All.sln --no-restore --verbosity ${{ needs.environment.outputs.verbosity }} -c ${{ needs.environment.outputs.configuration }}
-      - name: Test
-        run: dotnet test src/All.sln --no-build --verbosity ${{ needs.environment.outputs.verbosity }} -c ${{ needs.environment.outputs.configuration }} --filter Category!=SkipInCI
-      - name: Pack      
-        run: dotnet pack src/Amusoft.Templates/Amusoft.Templates.csproj -o "artifacts/nupkg" --no-build --verbosity ${{ needs.environment.outputs.verbosity }} -c ${{ needs.environment.outputs.configuration }} /p:VersionSuffix=${{ needs.environment.outputs.versionSuffix}}
-      - name: Inspect path
-        shell: pwsh        
-        run: Get-ChildItem -Path "artifacts/nupkg" 
-
-      - name: Release
-        run: dotnet nuget push "artifacts/nupkg/*.nupkg" -k $env:NUGETKEY -s https://api.nuget.org/v3/index.json
-        shell: pwsh
-        if: ${{ needs.environment.outputs.publishRelease == 'true' && ( github.event.pull_request.merged || github.event_name == 'workflow_dispatch' ) }}
+      - name: nuget secret verification
         env:
-          NUGETKEY: ${{ secrets.NUGET }}
+          NUGET: ${{ secrets.NUGET }}
+        if: "${{ env.NUGET == '' }}"
+        uses: actions/github-script@v3
+        with:
+          script: |
+            core.setFailed('"nuget" secret is missing')
+
+      - name: Setting up parameters
+        id: parameters
+        shell: pwsh
+        run: |
+          Write-Host "Setting up parameters"
+          
+          $branch = "master"
+          $conf = "${{github.event.inputs.configuration}}"
+          $verb = "${{github.event.inputs.verbosity}}"
+          $publ = "${{github.event.inputs.publish}}"
+          $removePrereleases = "${{github.event.inputs.removePrereleases}}"
+          $prefix = "${{github.event.inputs.versionPrefix}}"
+          $suffix = "${{github.event.inputs.versionSuffix}}"
+          $bnr = "${{github.run_number}}"
+          
+          $commitMode = "noop"          
+          if($commitMode -eq "noop" -and "${{github.event_name}}" -eq "workflow_dispatch") {
+              $commitMode = "dispatch" }
+          if($commitMode -eq "noop" -and "$branch|pull_request|closed|true" -eq "${{github.ref_name}}|${{github.event_name}}|${{github.event.action}}|${{github.event.pull_request.merged}}") {
+              $commitMode = "pushMerge" }
+          if($commitMode -eq "noop" -and "$branch|push" -eq "${{github.ref_name}}|${{github.event_name}}") {
+              $commitMode = "push" }
+          
+          $data = @{          #prefix         #suffix         #configuration  #verbosity  #publish    #removeprerelease                       
+              "dispatch" =    @("$prefix",    "$suffix",      "$conf",        "$verb",    "$publ",    "$removePrereleases")
+              "push" =        @("",           "alpha.$bnr",   "Release",      "n",        "true",     "false")
+              "pushMerge" =   @("",           "beta.$bnr",    "Release",      "n",        "true",     "false")
+              "noop" =        @("",           "noop",         "Release",      "n",        "false",    "false")
+          };
+          $names = @("versionPrefix","versionSuffix","configuration","verbosity","publish","removePrereleases")
+          
+          if($data[$commitMode] -eq $null){
+              Write-Host "Unidentified commit mode $commitMode"
+              echo "Commit mode could not be identified." >> $env:GITHUB_STEP_SUMMARY
+              exit 1;
+          }
+
+          $names += "package";
+          $names += "publishSymbols";
+          $names += "runTests";
+          $names += "runCoverage";
+
+          $data[$commitMode] += $data[$commitMode][4]
+          $data[$commitMode] += $data[$commitMode][4]
+          $data[$commitMode] += $data[$commitMode][4]
+          $data[$commitMode] += $data[$commitMode][4]
+          
+          foreach($item in $names){
+              $index = $names.IndexOf($item)
+              Write-Host "$item=$($data[$commitMode][$index])"
+              echo "$item=$($data[$commitMode][$index])" >> $env:GITHUB_OUTPUT
+              echo "$item=$($data[$commitMode][$index])" >> $env:GITHUB_STEP_SUMMARY
+          }
+          
+          echo "Identified commit mode $commitMode" >> $env:GITHUB_STEP_SUMMARY
+
+  package:
+    needs: parameters
+    uses: taori/actions/.github/workflows/nupkg.yml@v9
+    with:
+      solutionPath: src/All.sln
+      packProjects: src/Amusoft.Templates/Amusoft.Templates.csproj
+      versionSuffix: ${{ needs.parameters.outputs.versionSuffix }}
+      versionPrefix: ${{ needs.parameters.outputs.versionPrefix }}
+      package: ${{ needs.parameters.outputs.package == 'true' }}
+      publish: ${{ needs.parameters.outputs.publish == 'true' }}
+      publishSymbols: ${{ needs.parameters.outputs.publishSymbols == 'true' }}
+      removePrereleases: ${{ needs.parameters.outputs.removePrereleases == 'true' }}
+      skipTests: ${{ needs.parameters.outputs.runTests == 'false' }}
+      configuration: ${{ needs.parameters.outputs.configuration }}
+      verbosity: ${{ needs.parameters.outputs.verbosity }}
+      runCoverage: ${{ needs.parameters.outputs.runCoverage == 'true' }}
+      testArguments: "--filter Category!=SkipInCI"
+      concurrencyAbortable: true
+      coverageThreshold: '85 95'
+      dotnetVersion: 6.0.x
+    secrets:
+      nuget: ${{ secrets.NUGET }}
+      
